import { join, resolve } from "node:path"

import { appRoot, contentRoot } from "./content"

type Field = {
  name: string
  type: string
  arguments: string
}

export type GraphQLType = {
  name: string
  description: string
  fields: Array<Field>
}

const repoRoot = resolve(appRoot, "../..")
const indexerRoot = join(repoRoot, "apps/s03-indexer")
const sourceSchema = join(indexerRoot, "schema.graphql")
const target = join(contentRoot, "reference/graphql.generated.mdx")

export function parseSchema(source: string): Array<GraphQLType> {
  const types: Array<GraphQLType> = []
  const typePattern = /(?:"""([\s\S]*?)"""\s*)?type\s+(\w+)[^{]*\{([\s\S]*?)\}/g
  for (const match of source.matchAll(typePattern)) {
    const fields: Array<Field> = []
    for (const line of match[3].split("\n")) {
      const field = line.match(/^\s{2}(\w+)(?:\(([^)]*)\))?\s*:\s*(\S+)/)
      if (field)
        fields.push({
          name: field[1],
          arguments: field[2] ?? "",
          type: field[3],
        })
    }
    types.push({
      name: match[2],
      description: (match[1] ?? "").trim().replaceAll("\n", " "),
      fields,
    })
  }
  if (!types.length) throw new Error(`No GraphQL types found in ${sourceSchema}`)
  if (types.some((type) => !type.fields.length))
    throw new Error("Every GraphQL type must contain at least one field")
  return types
}

function renderType(type: GraphQLType) {
  const fields = type.fields
    .map(
      (field) =>
        `| \`${field.name}\` | \`${field.type}\` | ${field.arguments ? `\`${field.arguments}\`` : "-"} |`,
    )
    .join("\n")
  return `### ${type.name}\n\n${type.description || "No description provided."}\n\n| Field | Type | Arguments |\n| --- | --- | --- |\n${fields}`
}

export function renderGraphQLReference(types: Array<GraphQLType>) {
  const entityQueries = types
    .map(
      (type) =>
        `| \`${type.name[0].toLowerCase()}${type.name.slice(1)}\` | \`${type.name}\` | \`id: ID!\` |`,
    )
    .join("\n")
  const totalFields = types.reduce((count, type) => count + type.fields.length, 0)
  return `---
title: Indexer GraphQL schema
description: Generated reference for every SO4 indexer GraphQL type, field, query, and argument, including practical queries for positions, trades, and market state.
updated: 2026-08-25
status: stable
---

> Generated from \`apps/s03-indexer/schema.graphql\`. Do not edit this file. Run \`bun run --cwd apps/docs generate:graphql\` to regenerate it.

This reference covers ${types.length} schema types and ${totalFields} fields. Entity queries are exposed by the SubQuery GraphQL service.

## Example queries {#example-queries}

### Positions by account

\`\`\`graphql
query PositionsByAccount($account: String!) {
  positions(filter: { account: { equalTo: $account } }) {
    nodes { id market { id } account status sizeUsd isLong }
  }
}
\`\`\`

Example response:

\`\`\`json
{"data":{"positions":{"nodes":[]}}}
\`\`\`

### Recent trades

\`\`\`graphql
query RecentTrades {
  positionChanges(orderBy: TIMESTAMP_DESC, first: 10) {
    nodes { id market { id } account changeType executionPrice timestamp }
  }
}
\`\`\`

Example response:

\`\`\`json
{"data":{"positionChanges":{"nodes":[]}}}
\`\`\`

### Market state

\`\`\`graphql
query MarketState($key: String!) {
  markets(filter: { key: { equalTo: $key } }) {
    nodes { id key name status latestConfigSnapshot { oracle maxLeverage } positions { totalCount } }
  }
}
\`\`\`

Example response:

\`\`\`json
{"data":{"markets":{"nodes":[]}}}
\`\`\`

## Entity queries {#entity-queries}

The generated service provides a connection query and an ID lookup for each entity. Connection queries accept filtering, ordering, pagination, and field selection arguments according to the deployed SubQuery GraphQL server.

| Query | Returns | Arguments |
| --- | --- | --- |
${entityQueries}

## Schema types {#schema-types}

${types.map(renderType).join("\n\n")}
`
}

async function runCodegen() {
  const result = Bun.spawn(["bun", "run", "--cwd", indexerRoot, "codegen"], {
    cwd: repoRoot,
    stdout: "inherit",
    stderr: "inherit",
  })
  const exitCode = await result.exited
  if (exitCode !== 0)
    throw new Error(`Indexer codegen failed with exit code ${exitCode}`)
}

if (import.meta.main) {
  await runCodegen().catch((error) => {
    console.error(`Unable to generate GraphQL reference: ${error}`)
    process.exit(1)
  })
  const types = parseSchema(await Bun.file(sourceSchema).text())
  const output = renderGraphQLReference(types)
  if (process.argv.includes("--check")) {
    if ((await Bun.file(target).text().catch(() => "")) !== output) {
      console.error("GraphQL reference is stale. Run: bun run --cwd apps/docs generate:graphql")
      process.exit(1)
    }
    console.log("GraphQL reference matches the indexer schema.")
  } else {
    await Bun.write(target, output)
    console.log(`Generated ${types.length} GraphQL types and ${types.reduce((count, type) => count + type.fields.length, 0)} fields.`)
  }
}